#Create new patient.
post http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Pinku",
  "ssn": "9416662422",
  "occupation": "Accountant",
  "dateOfBirth": "1994-12-24",
  "gender": "male"
}

###
#Adding patient's entry., adding to Martin Riggs".
post http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "OccupationalHealthcare",
  # "type": "Hospital",
  "date": "2013-02-23",
  "specialist": "Amar abdullah"
}

###
get http://localhost:3001/api/patients